Added demonstration of kmeans #24.
cvlabmiet/cvclasses16 pull request #28
Opened 2016-10-03 18:17 UTC by atselousov

Демострация работы алгоритма k-means. На мой взгляд выполнены все требования кроме вывод гистограмм, но их не надо делать для алгоритма k-means.

Выбор центров кластеров:
![1](https://cloud.githubusercontent.com/assets/22117239/19048058/597e33da-89ad-11e6-9773-fb7c00982f32.png)

Если кластеры не выбраны руками, то они задаются случайно. Количество случайно выбранных центров задаётся через входные параметры.

Пример сегментации (зеленым помечены центры кластеров):
![kmeans_1_1](https://cloud.githubusercontent.com/assets/22117239/19048159/d1293844-89ad-11e6-9bc6-37a7ee8d0ef4.png)
![kmeans_1_2](https://cloud.githubusercontent.com/assets/22117239/19048165/d5e31fbc-89ad-11e6-9f0d-0681de69cf8b.png)
![kmeans_1_3](https://cloud.githubusercontent.com/assets/22117239/19048168/d8f3e966-89ad-11e6-817c-3b288eacb62c.png)
![kmeans_1_4](https://cloud.githubusercontent.com/assets/22117239/19048171/dc17a7f4-89ad-11e6-9474-1788ff627372.png)
![kmeans_1_5](https://cloud.githubusercontent.com/assets/22117239/19048173/decaa88e-89ad-11e6-8d4e-c5261d0c73da.png)
![kmeans_1_6](https://cloud.githubusercontent.com/assets/22117239/19048176/e20e3c9a-89ad-11e6-857b-98d0f6f5c2ed.png)

Пример вывода информации в консоль (затраченное время):
![2](https://cloud.githubusercontent.com/assets/22117239/19048189/f5d02acc-89ad-11e6-890a-d26327c24ba1.png)

2016-10-04 13:16 UTC, rgolovanov commented
@atselousov для этого метода сегментации гистограммы не нужны. Проставь галочки в issue напротив тех пунктов, которые были выполнены.

@whitemol ожидаем ревью

2016-10-04 13:45 UTC, atselousov commented
@rgolovanov В этой формуле (Your# + Lesson# - 1) mod 8, если я не ошибаюсь, надо сделать +1. Если так,  то мне надо назначить другого проверяющего? Или 8 приравнивается 0?

2016-10-04 14:19 UTC, rgolovanov commented
@atselousov, @cvlabmiet/students16 формула вызывает вопросы для граничного случая. Давайте договоримся, что 0 приравнивается 8.

Для 2го занятия такое распределение:
* 1 -> 2
* 2 -> 3
* ...
* 7 -> 8 ( хотя по формуле получается 0)
* 8 -> 1

2016-10-04 17:05 UTC, whitemol commented
@rgolovanov  Ревью сделан, замечаний нет.

2016-10-05 19:08 UTC, rgolovanov requested changes
@atselousov  у меня замечания есть. Посмотри пожалуйста.

2016-10-05 19:08 UTC, rgolovanov commented on lesson2/kmeans.cpp
> +    "{@filename      |      | Input image.                }"
Добавь значения по умолчанию: kmeans_test.png и .\ чтобы можно было запускать любой тест без параметров.

@cvlabmiet/students16 в своих демках тоже так сделайте, чтобы не приходилось перезапускать программу с разными параметрами для обработки тестовых демонстрационных изображений

2016-10-05 19:08 UTC, rgolovanov commented on lesson2/kmeans.cpp
> +	if (event == cv::EVENT_LBUTTONUP || !(flags & cv::EVENT_FLAG_LBUTTON))
"event == cv::EVENT_LBUTTONUP" можно убрать из проверки.

А что означает проверка на flags?

2016-10-05 19:08 UTC, rgolovanov commented on lesson2/kmeans.cpp
> +    } catch (...) {
тут пробельный отступ, хотя во всём файле используются табы. поправь пожалуйста

2016-10-05 19:08 UTC, rgolovanov commented on lesson2/kmeans.cpp
> +				if (distance < dst.at<double>(i, j))
Это смесь c++  и python?

по условию выполнится только одна строка. Остальные тоже должны? Если нет, то убери лишний отступ

2016-10-05 19:08 UTC, rgolovanov commented on lesson2/kmeans.cpp
> +		char key = (char)cv::waitKey();
в с++ настоятельно рекомендуется делать приведение типов с помощью xxx_cast<>() операторов

2016-10-05 19:08 UTC, rgolovanov commented on lesson2/kmeans.cpp
>  #include "stdafx.h"
Добавь стандартную шапку к файлу:
например:
///@File: main.cpp
///@Brief: Contains implementation of entry point of the application
///@Author: Roman Golovanov
///@Date: 08 September 2015

2016-10-05 19:08 UTC, rgolovanov commented on lesson2/kmeans.cpp
> +			if (std::abs(new_centers[i].x - centers[i].x) > 1 ||
Условие можно упростить используя функцию вычисления нормы: cv::norm(new_centers[i]-centers[i])

2016-10-05 19:08 UTC, rgolovanov commented on lesson2/kmeans.cpp
> +		if (exit_flag || itr > MAX_ITR) {
Если сегметация закончилась по причине превышения лимита, то об этом нужно сообщать пользователю.

2016-10-05 20:30 UTC, atselousov commented
@rgolovanov исправил.

2016-10-06 12:49 UTC, rgolovanov approved these changes

2016-10-06 12:50 UTC, merged