Lesson 2. Add otsu threshold algorithm. Issue #19
cvlabmiet/cvclasses16 pull request #29
Opened 2016-10-06 17:09 UTC by whitemol

Добавлена демонстрация работы метода Отцу. Это метод глобальной сегментации изображения.

Ввода пользователя не требуется.

Работа алгоритма начинается с нулевого порога. 
Зеленой точечкой помечен текущий порог на гистограмме.
![image](https://cloud.githubusercontent.com/assets/22376462/19161913/59d31f50-8bfe-11e6-959e-c555ccd41cbc.png)
![image](https://cloud.githubusercontent.com/assets/22376462/19161933/728a950a-8bfe-11e6-815f-79e1884945df.png)
![image](https://cloud.githubusercontent.com/assets/22376462/19161936/79eb0118-8bfe-11e6-9af9-6628fb47907b.png)
![image](https://cloud.githubusercontent.com/assets/22376462/19161950/8a52bf32-8bfe-11e6-9332-cf297b89c10c.png)

И продолжается до тех пор пока не будет найдено максимальное значение межклассовой вариации.

Одна из последующих итераций:
![image](https://cloud.githubusercontent.com/assets/22376462/19162020/d5e8e5f2-8bfe-11e6-867d-a793623996c4.png)
![image](https://cloud.githubusercontent.com/assets/22376462/19162012/ce84dce4-8bfe-11e6-89ab-6e88a0c262e7.png)
![image](https://cloud.githubusercontent.com/assets/22376462/19162026/dac64fce-8bfe-11e6-8ffb-12d0c6aa8d96.png)

И конечный вывод
![image](https://cloud.githubusercontent.com/assets/22376462/19162378/4ff25a26-8c00-11e6-918f-9877150ec067.png)
![image](https://cloud.githubusercontent.com/assets/22376462/19162353/31d0fc5a-8c00-11e6-9270-3e856a9147d5.png)
![image](https://cloud.githubusercontent.com/assets/22376462/19162356/354721fc-8c00-11e6-80ce-2b8d905cc95e.png)

2016-10-07 17:41 UTC, rgolovanov requested changes
Немного запутанная реализация получилась, но идея алгоритма видна. Есть некоторые замечания, которые стоит исправить.

2016-10-07 17:41 UTC, rgolovanov commented on lesson2/otsuthreshold.cpp
> +  end = chrono::system_clock::now();
по скриншотам видно, что время одной итерации почти секунда, что очень долго. Вероятно это связано с вызовами make_result и show_result - их стоит вынести из цикла.

2016-10-07 17:41 UTC, rgolovanov commented on lesson2/otsuthreshold.cpp
> +  threshold_value = 0;
Проще было бы иметь вспомогательную структуру для хранения всех этих параметров. Это больше как пожелание и рекомендация на будущее.

2016-10-07 17:41 UTC, rgolovanov commented on lesson2/otsuthreshold.cpp
> +    if (wB == 0)
Можно добавить ещё || img_hist.at<float>(t) == 0, чтобы перескочить через нулевые элементы гистограммы

2016-10-07 18:37 UTC, whitemol commented
@rgolovanov Обновлено

2016-10-07 19:13 UTC, rgolovanov commented
@whitemol хорошо. Теперь осталось дождаться, когда @LenaBuranova тоже сделает ревью.

2016-10-07 22:14 UTC, LenaBuranova commented
Вроде, всё хорошо.

2016-10-08 05:42 UTC, rgolovanov approved these changes

2016-10-08 05:43 UTC, merged