Fixes #22 Added split and merge segmentation algorithm demo.
cvlabmiet/cvclasses16 pull request #32
Opened 2016-10-08 05:19 UTC by minaew

Добавлен демонстрационный пример работы алгоритма сегментации split-and-merge.

Изначально все изображение рассматривается как один фрагмент.
Затем происходит итеративное разбиение каждого фрагмента на подобласти или слияние смежных подобластей, пока все они не станут однородными или пока не будет достигнуто желаемое количество фрагментов.

Для хранения связей между родительскими областями и подобластями используется структура данных квадродерево. 

![screen1](https://cloud.githubusercontent.com/assets/22275840/19210560/ceef2ee2-8d2e-11e6-8148-4c9375c2a62d.png)
![screen2](https://cloud.githubusercontent.com/assets/22275840/19210563/d32612d2-8d2e-11e6-8ff4-3ea4243fb1d4.png)

2016-10-09 19:59 UTC, rgolovanov requested changes
Ожидаю исправления замечаний

2016-10-09 19:59 UTC, rgolovanov commented on lesson2/splitAndMerge.cpp
> +	cv::CommandLineParser parser(argc, argv, "{help h | | }{ @input | split.bmp | }");
А где само тестовое изображение?

2016-10-09 19:59 UTC, rgolovanov commented on lesson2/splitAndMerge.cpp
> +	QuadTree(cv::Mat* in_image, int in_coord_x, int in_coord_y, int in_size_x, int in_size_y)
лучше было бы использовать структуры cv::Point и cv::Size - мы их обсуждали на 1й лекции

2016-10-09 19:59 UTC, rgolovanov commented on lesson2/splitAndMerge.cpp
> +			delete m_child1;
не обязательно проверять указалтель при вызове delete, а лучше вообще использовать std::unique_ptr<>

2016-10-09 19:59 UTC, rgolovanov commented on lesson2/splitAndMerge.cpp
> +	cv::Mat* m_image;
m_image можно хранить по значению. Как мы помним копирования не будет, так cv::Mat ведет себя как std::shared_ptr<>

2016-10-09 19:59 UTC, rgolovanov commented on lesson2/splitAndMerge.cpp
> +///@File: splitAndMerge.cpp
новый файл ещё нужно добавить в проекст lesson2.vcxproj - то есть в пулл-риквесте должен быть и этот файл тоже

2016-10-20 19:34 UTC, minaew commented
Тестовое изображение: lesson2/split.bmp

2016-10-20 21:55 UTC, rgolovanov requested changes
Ещё немного замечаний + нужно сделать ребэйз: git pull --rebase и устранить конфликты.

2016-10-20 21:55 UTC, rgolovanov commented on lesson2/lesson2.vcxproj
> -﻿<?xml version="1.0" encoding="utf-8"?>
слишком сильно всё изменилось

2016-10-20 21:55 UTC, rgolovanov commented on lesson2/lesson2.vcxproj
> -﻿<?xml version="1.0" encoding="utf-8"?>
должны быть изменены всего несколько строк, там где добавляется файл

2016-10-20 21:55 UTC, rgolovanov commented on lesson2/splitAndMerge.cpp
> +	QuadTree(cv::Mat in_image, cv::Point in_position, cv::Size in_size)
Аргументы передаются по значению, а это плохо (долго) при вызове функции. Лучше использовать передачу по ссылке, а ещё лучше по константной ссылке. В данном случае это возможно.

2016-10-20 21:55 UTC, rgolovanov commented on lesson2/splitAndMerge.cpp
> +	QuadTree* m_child1;
От хранения сырых указателей (raw pointers) лучше отказаться. Опятже тут можно использовать **std::unique_ptr**.

Создание объектов необходимо делать с помощью функции **std::make_unique**, чтобы не использовать операто **new** в явном виде.

2016-10-20 21:55 UTC, rgolovanov commented on lesson2/splitAndMerge.cpp
> +}
файл должен заканчиваться пустой строкой. воизбежании проблем с компилятором.

2016-10-21 15:29 UTC, minaew commented on lesson2/splitAndMerge.cpp
> +	QuadTree* m_child1;
Я храню указатели на объекты квадродерева как члены родительского объекта и запоминаю их для обработки. То есть, хранятся два одинаковых указателя. std::unique_ptr не позволяет такого делать. В таком случае, стоит использовать std::shared_ptr?

2016-10-21 15:29 UTC, minaew commented on lesson2/lesson2.vcxproj
> -﻿<?xml version="1.0" encoding="utf-8"?>
Оставил изменения только в списке фалов исходного кода.

2016-10-25 10:38 UTC, merged

2016-10-25 10:38 UTC, rgolovanov commented
Принято