Lesson 2. Добавлен код для Gaussian Mixture Modelling. Close #20
cvlabmiet/cvclasses16 pull request #42
Opened 2016-10-18 19:02 UTC by SergEfremenkov

# Краткое описание алгоритма:
1) Вычисляем гистограмму распределения уровней серого в исходном изображении.
2) Задаются начальные параметры гауссиана.
3) Используем алгоритм максимизации вероятностей (EM) для уточнений параметров гауссиана.
4) Если вычисленная ошибка на шаге 3 меньше, чем предварительно определенное пороговое значение или число итераций больше T, то останавливаемся и выводим результаты. Иначе - возвращаемся на шаг 3.
5) Добавляем новые параметры гауссиана и переходим на этап 2.
6) В конце работы алгоритма выбираем оптимальное пороговое значение, как среднее арифметическое всех математических ожиданий.
# Пример работы алгоритма
1) Исходное изображение
![cameraman](https://cloud.githubusercontent.com/assets/22372080/19492043/dd44728e-957d-11e6-8b39-d1183b3d595b.png)
2) Изображение в градациях серого
![default](https://cloud.githubusercontent.com/assets/22372080/19492051/e42234ce-957d-11e6-8dd4-7d3e02c7a1b8.png)
3) Изображение после пороговой обработки
![default](https://cloud.githubusercontent.com/assets/22372080/19492058/e8a5407c-957d-11e6-92ee-a767f47745b4.png)
4) Гистограмма изображения с порогом
![default](https://cloud.githubusercontent.com/assets/22372080/19492063/edee3390-957d-11e6-87a9-728e4d594634.png)
5) Пример выводимой информации в консоли
![default](https://cloud.githubusercontent.com/assets/22372080/19492102/0dc95564-957e-11e6-8267-cb3fba1bc124.png)

2016-10-18 19:23 UTC, SergEfremenkov commented
Почему-то не отображается исходное изображение.

2016-10-18 19:55 UTC, rgolovanov requested changes

2016-10-18 19:55 UTC, rgolovanov commented on lesson1/lesson1.vcxproj
> -    <PlatformToolset>v120</PlatformToolset>
Это изменение нужно откатить

2016-10-18 19:55 UTC, rgolovanov commented on lesson2/gmm.cpp
> +	for_each(means.begin(), means.end(), [](double value)
c++11:
for(const auto& val : means)

2016-10-18 19:55 UTC, rgolovanov commented on lesson2/gmm.cpp
> +			whriteImage(outputPath);
По условию задания нужно сохранять промежуточные результаты в файлы, а не только конечные картинки.

2016-10-18 19:55 UTC, rgolovanov commented on lesson2/gmm.cpp
> +	imshow("Histogram of image", histImage);
Балл бы не плохо на гистограмме изображения показываться каждую гауссиану

2016-10-18 19:55 UTC, rgolovanov commented on lesson2/gmm.cpp
> +	for (int j = 0; j < numGaus; ++j)
Добавь пожалуйста комментарии к каждому вложенному блоку кода

2016-10-18 19:55 UTC, rgolovanov commented on lesson2/main.cpp
> +int gmm(int, char**); /*TODO: implement in separate file*/
А комментарий к функции можно удалить

2016-10-18 19:55 UTC, rgolovanov commented on reveal.js
> +Subproject commit bac187f3a0f7e8f92d33ca0258fe2e96553d2930
Тут сабмодули не нужны

2016-10-18 19:57 UTC, rgolovanov commented
Есть конфликт с веткой мастер. Нужно сделать ребэйз: git pull --rebase

2016-10-18 20:15 UTC, SergEfremenkov commented on lesson2/gmm.cpp
> +			whriteImage(outputPath);
Промежуточные результаты: математические ожидания и дисперсии гауссианов? Просто других промежуточных данных в данном алгоритме нет.

2016-10-19 00:59 UTC, SergEfremenkov commented
Исправил все замечания, кроме отрисовки гауссиан на гистограмме изображения.

2016-10-19 06:25 UTC, rgolovanov requested changes
Нужно удалить файл с результатами из репозитория.

и ещё

> > По условию задания нужно сохранять промежуточные результаты в файлы, а не только конечные картинки.
> > Имелось в виду сохранение изображения для каждой итерации.

2016-10-19 06:25 UTC, rgolovanov commented on lesson2/gmm/intermediate_data.txt
> +| � Gaussian: 0 | Iteration number: 0 | Difference Log-likelihoods:31.7745 | Mean: 0.27 | Variance:0.1 | Weight: 0.333333 |
этот файл не нужен в репозитории

2016-10-19 10:40 UTC, SergEfremenkov commented
Все исправил

2016-10-19 11:19 UTC, rgolovanov requested changes
осталось 2 вопроса

2016-10-19 11:19 UTC, rgolovanov commented on lesson2/gmm.cpp
> +	//Вычисляем оптимальное пороговое значение, как среднее арифметическое всех математических ожиданий
Разве это будет оптимальное значение порога? Оптимальный порог находится на пересечении двух гауссиан!

2016-10-19 11:19 UTC, rgolovanov commented on lesson2/gmm.cpp
> +			whriteImage(outputPath);
Для демонстрации можно сохранять значения дисперсии и матожидания на каждой итерации для каждой гауссианы.

Далее, двигаясь по наборам этих значений, вычислять оптимальный порог для каждой пары значений обеих гауссиан и сбрасывать результат сегментации текущего порога в файл.

2016-10-19 15:50 UTC, SergEfremenkov commented
2-ое замечание нереализуемо, так как алгоритм EM, который используется для решения задачи минимизации, для каждой гауссианы сходится за различное число итераций.

2016-10-19 15:54 UTC, SergEfremenkov commented
Пороговое значение я искал, как приведено в статье, которую вы рекомендовали (In the end, we choose the optimal threshold which is the average of these means). Могу исправить на вариант через пересечение гауссиан.

2016-10-19 20:29 UTC, SergEfremenkov commented
Реализовал вывод промежуточных результатов пороговой сегментации для каждой пары гауссиан. 
Пороговое значение я искал, как приведено в статье, которую Вы рекомендовали (In the end, we choose the optimal threshold which is the average of these means). Могу исправить на вариант через пересечение гауссиан.

2016-10-20 05:13 UTC, rgolovanov commented
1. порог нужно выбирать по пересечению гауссиан

2. Количество итераций по каждой гауссине разное - это понятно. Например 10 для одной и 15 для другой. Можно выводить изображения получаемые для первых 10 пар, а потом для оставшихся 5 значений второй гауссианы, фиксируя при этом первую на последнем значении.

2016-10-20 15:34 UTC, SergEfremenkov commented
Все исправил

2016-10-20 21:35 UTC, merged